server:
  port: 9010

spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: postgres
    password: "123"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "EstaEsUnaLlaveSecretaMuyLargaYSeguraParaECommerce2026"
  expirationMs: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
