spring:
  application:
    name: ms-product

  datasource:
    url: jdbc:postgresql://localhost:5433/products_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 9015

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:EstaEsUnaLlaveSecretaMuyLargaYSeguraParaECommerce2026}
  expirationMs: 86400000
